version: "3.5"

services:
  todo-ls-backend:
    container_name: todo_ls_backend
    build: https://github.com/H36615/todo-ls-backend.git
    image: todo-ls-backend
    env_file: .env
    networks:
      - db-network
    ports:
      - "${BACKEND_CONTAINER_PORT}:${BACKEND_APPLICATION_PORT}"

  todo-ls-frontend:
    container_name: todo_ls_frontend
    build: https://github.com/H36615/todo-ls-frontend.git
    image: todo-ls-frontend
    env_file: .env
    ports:
      - "${FRONTEND_CONTAINER_PORT}:${FRONTEND_APPLICATION_PORT}"

  todo-ls-db:
    container_name: todo_ls_db
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db-network
    restart: unless-stopped

  todo-ls-pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-3022}:80"
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
